### ISSUE TITLE
Chrome voting bug

### ISSUE THREAD

**Issue by soulBit** [DistributedCollective/governance-dapp#118]
"Little bug with voting on Chrome. When you try to open the active proposal on a new tab/window, it won't load. The only way to vote is to click on the Active proposal and do it in the same window/tab. "

**Comment by tiltom** [comment]
I don't think this is a bug since it has never worked that way. The reason why you cannot vote in a new tab is pretty simple - a proposal in a new tab is not connected to a wallet because it's basically a new instance of the app.

However, a solution is not so simple - we would need to create a new page and route because with the current implementation of `ProposalDetailsPage` is not possible to show it user-friendly in a new tab (because it's always just used as a modal dialog). Users would also need to engage wallet twice (unless we can solve it somehow but it wouldn't be easy).
 
Also, I don't think we should spend development time on this since the current solution with a modal works perfectly and opening in a new tab will not bring any additional benefits. Btw - it's the same situation with `Propose`.
